<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Assistant.NET</Product>
    <Authors>iotbusters</Authors>
    <RepositoryType>github</RepositoryType>
    <RepositoryUrl>https://github.com/iotbusters/assistant.net.dynamics</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

</Project>
