<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Assistant.Net.Dynamics</RootNamespace>
    <AssemblyName>assistant.net.dynamics.proxy.analyzer</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DevelopmentDependency>true</DevelopmentDependency>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proxy.Builder\Proxy.Builder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>

  <PropertyGroup>
    <Product>Assistant.NET</Product>
    <RepositoryType>github</RepositoryType>
    <PackageTags>dynamic proxy analyzer</PackageTags>
    <Description>Code analysis and proxy generation tool.</Description>
    <RepositoryUrl>https://github.com/iotbusters/assistant.net.dynamics</RepositoryUrl>
    <PackageProjectUrl>https://github.com/iotbusters/assistant.net.dynamics/blob/master/README.md#assistantnetdynamicsproxyanalyzer</PackageProjectUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE" Link="LICENSE" Pack="true" PackagePath="" />
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

</Project>
